### ISSUE TITLE
筛选条件最低评分数无法正常工作

### ISSUE THREAD

**Issue by Wycers** [SUSTechFlow/web#2]
![image](https://user-images.githubusercontent.com/17094433/75148472-b1260500-573a-11ea-9cb9-bb41f3a7f1bd.png)

如题

**Comment by JohnWestonNull** [comment]
`const rateFilter = requiredRatings => course => course.ratings >= requiredRatings;`
To 
`const rateFilter = requiredRatings => course => course.ratings >= requiredRatings*5;`
It's a problem of the above code, will be fixed in no time.

**Comment by JohnWestonNull** [comment]
Repaired, closing.
